/**
 * Read web dist files and generate a TypeScript module that exports them
 * as a Record<path, { content: string; contentType: string }>.
 * Run this after build:web and before bun build --compile.
 */
import { join, extname } from "node:path";

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

const distDir = join(import.meta.dir, "..", "src", "web", "dist");
const glob = new Bun.Glob("**/*");
const entries: Record<string, { content: string; contentType: string }> = {};

for await (const path of glob.scan({ cwd: distDir })) {
  const fullPath = join(distDir, path);
  const file = Bun.file(fullPath);
  const ext = extname(path);
  const contentType = MIME_TYPES[ext] ?? "application/octet-stream";
  const content = await file.text();
  const key = `/${path}`;
  entries[key] = { content, contentType };
}

const output = `// Auto-generated by scripts/embed-web.ts — do not edit
export const WEB_ASSETS: Record<string, { content: string; contentType: string }> = ${JSON.stringify(entries, null, 2)};
`;

const outPath = join(import.meta.dir, "..", "src", "web", "embedded.ts");
await Bun.write(outPath, output);
console.log(`Embedded ${Object.keys(entries).length} files into ${outPath}`);
